// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zinger.Data;

namespace Zinger.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210404070045_addManyToMany")]
    partial class addManyToMany
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Zinger.Models.Hashtags", b =>
                {
                    b.Property<string>("Hashtag")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Zinger_ID")
                        .HasColumnType("int");

                    b.HasKey("Hashtag");

                    b.ToTable("Hashtags");
                });

            modelBuilder.Entity("Zinger.Models.Users", b =>
                {
                    b.Property<int>("U_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Admin_User")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Date_of_Birth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Display_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Middle_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass_word")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Handle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("U_ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Zinger.Models.UsersZingers", b =>
                {
                    b.Property<int>("U_ID")
                        .HasColumnType("int");

                    b.Property<int>("Zinger_ID")
                        .HasColumnType("int");

                    b.Property<int?>("UsersU_ID")
                        .HasColumnType("int");

                    b.Property<int?>("ZingersZinger_ID")
                        .HasColumnType("int");

                    b.HasKey("U_ID", "Zinger_ID");

                    b.HasIndex("UsersU_ID");

                    b.HasIndex("ZingersZinger_ID");

                    b.ToTable("UsersZingers");
                });

            modelBuilder.Entity("Zinger.Models.Zinger_Replies", b =>
                {
                    b.Property<int>("Replying_Zinger_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_Time_Stamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("Replying_U_ID")
                        .HasColumnType("int");

                    b.Property<string>("Zinger_Reply_Content")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Replying_Zinger_ID");

                    b.ToTable("Zinger_Replies");
                });

            modelBuilder.Entity("Zinger.Models.Zingers", b =>
                {
                    b.Property<int>("Zinger_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_Time_Stamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hashtag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zinger_Content")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Zinger_ID");

                    b.ToTable("Zingers");
                });

            modelBuilder.Entity("Zinger.Models.ZingersHashtags", b =>
                {
                    b.Property<int>("Zinger_ID")
                        .HasColumnType("int");

                    b.Property<string>("Hashtag")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HashtagsHashtag")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ZingersZinger_ID")
                        .HasColumnType("int");

                    b.HasKey("Zinger_ID", "Hashtag");

                    b.HasIndex("HashtagsHashtag");

                    b.HasIndex("ZingersZinger_ID");

                    b.ToTable("ZingersHashtags");
                });

            modelBuilder.Entity("Zinger.Models.ZingersZinger_Replies", b =>
                {
                    b.Property<int>("Zinger_ID")
                        .HasColumnType("int");

                    b.Property<int>("Replying_Zinger_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Zinger_RepliesReplying_Zinger_ID")
                        .HasColumnType("int");

                    b.Property<int?>("ZingersZinger_ID")
                        .HasColumnType("int");

                    b.HasKey("Zinger_ID", "Replying_Zinger_ID");

                    b.HasIndex("Zinger_RepliesReplying_Zinger_ID");

                    b.HasIndex("ZingersZinger_ID");

                    b.ToTable("ZingersZinger_Replies");
                });

            modelBuilder.Entity("Zinger.Models.UsersZingers", b =>
                {
                    b.HasOne("Zinger.Models.Users", "Users")
                        .WithMany("UsersZingers")
                        .HasForeignKey("UsersU_ID");

                    b.HasOne("Zinger.Models.Zingers", "Zingers")
                        .WithMany("UsersZingers")
                        .HasForeignKey("ZingersZinger_ID");

                    b.Navigation("Users");

                    b.Navigation("Zingers");
                });

            modelBuilder.Entity("Zinger.Models.ZingersHashtags", b =>
                {
                    b.HasOne("Zinger.Models.Hashtags", "Hashtags")
                        .WithMany("ZingersHashtags")
                        .HasForeignKey("HashtagsHashtag");

                    b.HasOne("Zinger.Models.Zingers", "Zingers")
                        .WithMany("ZingersHashtags")
                        .HasForeignKey("ZingersZinger_ID");

                    b.Navigation("Hashtags");

                    b.Navigation("Zingers");
                });

            modelBuilder.Entity("Zinger.Models.ZingersZinger_Replies", b =>
                {
                    b.HasOne("Zinger.Models.Zinger_Replies", "Zinger_Replies")
                        .WithMany("ZingersZinger_Replies")
                        .HasForeignKey("Zinger_RepliesReplying_Zinger_ID");

                    b.HasOne("Zinger.Models.Zingers", "Zingers")
                        .WithMany("ZingersZinger_Replies")
                        .HasForeignKey("ZingersZinger_ID");

                    b.Navigation("Zinger_Replies");

                    b.Navigation("Zingers");
                });

            modelBuilder.Entity("Zinger.Models.Hashtags", b =>
                {
                    b.Navigation("ZingersHashtags");
                });

            modelBuilder.Entity("Zinger.Models.Users", b =>
                {
                    b.Navigation("UsersZingers");
                });

            modelBuilder.Entity("Zinger.Models.Zinger_Replies", b =>
                {
                    b.Navigation("ZingersZinger_Replies");
                });

            modelBuilder.Entity("Zinger.Models.Zingers", b =>
                {
                    b.Navigation("UsersZingers");

                    b.Navigation("ZingersHashtags");

                    b.Navigation("ZingersZinger_Replies");
                });
#pragma warning restore 612, 618
        }
    }
}
