// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zinger.Data;

namespace Zinger.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Zinger.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date_of_Birth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Display_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("First_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Middle_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("User_Handle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Zinger.Models.Hashtags", b =>
                {
                    b.Property<string>("Hashtag")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("Zinger_ID")
                        .HasColumnType("int");

                    b.HasKey("Hashtag");

                    b.ToTable("Hashtags");
                });

            modelBuilder.Entity("Zinger.Models.Users", b =>
                {
                    b.Property<int>("U_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Admin_User")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Date_of_Birth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Display_Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Email_Address")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Middle_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pass_word")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("User_Handle")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("U_ID");

                    b.HasIndex("User_Handle")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            U_ID = 20,
                            Admin_User = false,
                            Date_of_Birth = new DateTime(1986, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Display_Name = "Jonny5",
                            Email_Address = "jonny5@number5.com",
                            First_Name = "Jonny",
                            Last_Name = "Five",
                            Middle_Name = "",
                            Pass_word = "P@$$W0rd",
                            User_Handle = "@Number5"
                        });
                });

            modelBuilder.Entity("Zinger.Models.UsersZingers", b =>
                {
                    b.Property<int>("U_ID")
                        .HasColumnType("int");

                    b.Property<int>("Zinger_ID")
                        .HasColumnType("int");

                    b.Property<int?>("UsersU_ID")
                        .HasColumnType("int");

                    b.Property<int?>("ZingersZinger_ID")
                        .HasColumnType("int");

                    b.HasKey("U_ID", "Zinger_ID");

                    b.HasIndex("UsersU_ID");

                    b.HasIndex("ZingersZinger_ID");

                    b.ToTable("UsersZingers");
                });

            modelBuilder.Entity("Zinger.Models.Zinger_Replies", b =>
                {
                    b.Property<int>("Replying_Zinger_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("Date_Time_Stamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Replying_U_ID")
                        .HasColumnType("int");

                    b.Property<string>("Zinger_Reply_Content")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Replying_Zinger_ID");

                    b.ToTable("Zinger_Replies");
                });

            modelBuilder.Entity("Zinger.Models.Zingers", b =>
                {
                    b.Property<int>("Zinger_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("Date_Time_Stamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Hashtag")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Zinger_Content")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Zinger_ID");

                    b.ToTable("Zingers");
                });

            modelBuilder.Entity("Zinger.Models.ZingersHashtags", b =>
                {
                    b.Property<int>("Zinger_ID")
                        .HasColumnType("int");

                    b.Property<string>("Hashtag")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("HashtagsHashtag")
                        .HasColumnType("nvarchar(400)");

                    b.Property<int?>("ZingersZinger_ID")
                        .HasColumnType("int");

                    b.HasKey("Zinger_ID", "Hashtag");

                    b.HasIndex("HashtagsHashtag");

                    b.HasIndex("ZingersZinger_ID");

                    b.ToTable("ZingersHashtags");
                });

            modelBuilder.Entity("Zinger.Models.ZingersZinger_Replies", b =>
                {
                    b.Property<int>("Zinger_ID")
                        .HasColumnType("int");

                    b.Property<int>("Replying_Zinger_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Zinger_RepliesReplying_Zinger_ID")
                        .HasColumnType("int");

                    b.Property<int?>("ZingersZinger_ID")
                        .HasColumnType("int");

                    b.HasKey("Zinger_ID", "Replying_Zinger_ID");

                    b.HasIndex("Zinger_RepliesReplying_Zinger_ID");

                    b.HasIndex("ZingersZinger_ID");

                    b.ToTable("ZingersZinger_Replies");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Zinger.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Zinger.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zinger.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Zinger.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zinger.Models.UsersZingers", b =>
                {
                    b.HasOne("Zinger.Models.Users", "Users")
                        .WithMany("UsersZingers")
                        .HasForeignKey("UsersU_ID");

                    b.HasOne("Zinger.Models.Zingers", "Zingers")
                        .WithMany("UsersZingers")
                        .HasForeignKey("ZingersZinger_ID");

                    b.Navigation("Users");

                    b.Navigation("Zingers");
                });

            modelBuilder.Entity("Zinger.Models.ZingersHashtags", b =>
                {
                    b.HasOne("Zinger.Models.Hashtags", "Hashtags")
                        .WithMany("ZingersHashtags")
                        .HasForeignKey("HashtagsHashtag");

                    b.HasOne("Zinger.Models.Zingers", "Zingers")
                        .WithMany("ZingersHashtags")
                        .HasForeignKey("ZingersZinger_ID");

                    b.Navigation("Hashtags");

                    b.Navigation("Zingers");
                });

            modelBuilder.Entity("Zinger.Models.ZingersZinger_Replies", b =>
                {
                    b.HasOne("Zinger.Models.Zinger_Replies", "Zinger_Replies")
                        .WithMany("ZingersZinger_Replies")
                        .HasForeignKey("Zinger_RepliesReplying_Zinger_ID");

                    b.HasOne("Zinger.Models.Zingers", "Zingers")
                        .WithMany("ZingersZinger_Replies")
                        .HasForeignKey("ZingersZinger_ID");

                    b.Navigation("Zinger_Replies");

                    b.Navigation("Zingers");
                });

            modelBuilder.Entity("Zinger.Models.Hashtags", b =>
                {
                    b.Navigation("ZingersHashtags");
                });

            modelBuilder.Entity("Zinger.Models.Users", b =>
                {
                    b.Navigation("UsersZingers");
                });

            modelBuilder.Entity("Zinger.Models.Zinger_Replies", b =>
                {
                    b.Navigation("ZingersZinger_Replies");
                });

            modelBuilder.Entity("Zinger.Models.Zingers", b =>
                {
                    b.Navigation("UsersZingers");

                    b.Navigation("ZingersHashtags");

                    b.Navigation("ZingersZinger_Replies");
                });
#pragma warning restore 612, 618
        }
    }
}
